apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-result-app
spec:
  containers:
    - name: result-app-container
      image: drxaero/examplevotingtapp_result:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
