apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app-container
      image: drxaero/examplevotingapp_vote:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
